#                     Copyright © 2020 Joseph Policarpio

#     Battle Anki, an addon for Anki, a program for studying flash cards.

#     This file is part of Battle Anki
#
#     Battle Anki is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License (AGPL)
#     version 3 of the License, as published by the Free Software Foundation.
#                               AGPL-3.0-only.
#
#     Battle Anki is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatMainWin(object):
    def setupUi(self, BatMainWin):
        BatMainWin.setObjectName("BatMainWin")
        BatMainWin.setEnabled(True)
        BatMainWin.resize(410, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BatMainWin.sizePolicy().hasHeightForWidth())
        BatMainWin.setSizePolicy(sizePolicy)
        BatMainWin.setMinimumSize(QtCore.QSize(410, 410))
        BatMainWin.setMaximumSize(QtCore.QSize(410, 410))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../battle_anki_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BatMainWin.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BatMainWin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(410, 410))
        self.centralwidget.setMaximumSize(QtCore.QSize(410, 410))
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 400, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(400, 400))
        self.stackedWidget.setMaximumSize(QtCore.QSize(400, 400))
        self.stackedWidget.setMouseTracking(True)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.tableWidget_users_connected = QtWidgets.QTableWidget(self.page_1)
        self.tableWidget_users_connected.setGeometry(QtCore.QRect(20, 90, 200, 250))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_users_connected.sizePolicy().hasHeightForWidth())
        self.tableWidget_users_connected.setSizePolicy(sizePolicy)
        self.tableWidget_users_connected.setMinimumSize(QtCore.QSize(200, 250))
        self.tableWidget_users_connected.setMaximumSize(QtCore.QSize(200, 250))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(179, 179, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 179, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 179, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tableWidget_users_connected.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget_users_connected.setFont(font)
        self.tableWidget_users_connected.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tableWidget_users_connected.setMouseTracking(True)
        self.tableWidget_users_connected.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_users_connected.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tableWidget_users_connected.setAutoFillBackground(False)
        self.tableWidget_users_connected.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget_users_connected.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_users_connected.setLineWidth(2)
        self.tableWidget_users_connected.setMidLineWidth(0)
        self.tableWidget_users_connected.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_users_connected.setAutoScroll(False)
        self.tableWidget_users_connected.setAutoScrollMargin(0)
        self.tableWidget_users_connected.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_users_connected.setTabKeyNavigation(False)
        self.tableWidget_users_connected.setProperty("showDropIndicator", False)
        self.tableWidget_users_connected.setDragDropOverwriteMode(False)
        self.tableWidget_users_connected.setAlternatingRowColors(False)
        self.tableWidget_users_connected.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_users_connected.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_users_connected.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget_users_connected.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_users_connected.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget_users_connected.setShowGrid(False)
        self.tableWidget_users_connected.setWordWrap(False)
        self.tableWidget_users_connected.setCornerButtonEnabled(False)
        self.tableWidget_users_connected.setRowCount(0)
        self.tableWidget_users_connected.setColumnCount(3)
        self.tableWidget_users_connected.setObjectName("tableWidget_users_connected")
        self.tableWidget_users_connected.horizontalHeader().setVisible(True)
        self.tableWidget_users_connected.horizontalHeader().setDefaultSectionSize(135)
        self.tableWidget_users_connected.horizontalHeader().setHighlightSections(False)
        self.tableWidget_users_connected.horizontalHeader().setMinimumSectionSize(1)
        self.tableWidget_users_connected.verticalHeader().setVisible(False)
        self.tableWidget_users_connected.verticalHeader().setHighlightSections(False)
        self.lab_users_connected = QtWidgets.QLabel(self.page_1)
        self.lab_users_connected.setGeometry(QtCore.QRect(40, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lab_users_connected.setFont(font)
        self.lab_users_connected.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_users_connected.setWordWrap(True)
        self.lab_users_connected.setObjectName("lab_users_connected")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page_1)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(230, 60, 131, 42))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.numcards_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.numcards_layout.setContentsMargins(0, 0, 0, 0)
        self.numcards_layout.setObjectName("numcards_layout")
        self.lab_numcards = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_numcards.setFont(font)
        self.lab_numcards.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lab_numcards.setObjectName("lab_numcards")
        self.numcards_layout.addWidget(self.lab_numcards)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.spinbox_bdecksize = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinbox_bdecksize.setFont(font)
        self.spinbox_bdecksize.setMouseTracking(True)
        self.spinbox_bdecksize.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinbox_bdecksize.setMaximum(500)
        self.spinbox_bdecksize.setObjectName("spinbox_bdecksize")
        self.verticalLayout_3.addWidget(self.spinbox_bdecksize)
        self.lab_max_cards = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lab_max_cards.setFont(font)
        self.lab_max_cards.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_max_cards.setObjectName("lab_max_cards")
        self.verticalLayout_3.addWidget(self.lab_max_cards)
        self.numcards_layout.addLayout(self.verticalLayout_3)
        self.but_sendittt = QtWidgets.QPushButton(self.page_1)
        self.but_sendittt.setGeometry(QtCore.QRect(50, 350, 140, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.but_sendittt.setFont(font)
        self.but_sendittt.setObjectName("but_sendittt")
        self.checkBox_apply_resched = QtWidgets.QCheckBox(self.page_1)
        self.checkBox_apply_resched.setGeometry(QtCore.QRect(230, 290, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_apply_resched.setFont(font)
        self.checkBox_apply_resched.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_apply_resched.setChecked(True)
        self.checkBox_apply_resched.setTristate(False)
        self.checkBox_apply_resched.setObjectName("checkBox_apply_resched")
        self.lab_batform_connected = QtWidgets.QLabel(self.page_1)
        self.lab_batform_connected.setEnabled(True)
        self.lab_batform_connected.setGeometry(QtCore.QRect(30, 0, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lab_batform_connected.setFont(font)
        self.lab_batform_connected.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_batform_connected.setWordWrap(True)
        self.lab_batform_connected.setObjectName("lab_batform_connected")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.page_1)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(230, 110, 161, 38))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_match_q = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_match_q.setFont(font)
        self.checkBox_match_q.setObjectName("checkBox_match_q")
        self.verticalLayout_4.addWidget(self.checkBox_match_q)
        self.lab_matched_desc = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lab_matched_desc.setMaximumSize(QtCore.QSize(185, 16777215))
        self.lab_matched_desc.setWordWrap(True)
        self.lab_matched_desc.setObjectName("lab_matched_desc")
        self.verticalLayout_4.addWidget(self.lab_matched_desc)
        self.progressBar_loading = QtWidgets.QProgressBar(self.page_1)
        self.progressBar_loading.setGeometry(QtCore.QRect(50, 0, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_loading.setFont(font)
        self.progressBar_loading.setProperty("value", 1)
        self.progressBar_loading.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_loading.setTextVisible(True)
        self.progressBar_loading.setInvertedAppearance(False)
        self.progressBar_loading.setObjectName("progressBar_loading")
        self.lab_based_on_answers = QtWidgets.QLabel(self.page_1)
        self.lab_based_on_answers.setGeometry(QtCore.QRect(240, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lab_based_on_answers.setFont(font)
        self.lab_based_on_answers.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_based_on_answers.setWordWrap(True)
        self.lab_based_on_answers.setObjectName("lab_based_on_answers")
        self.lab_today_only_explain = QtWidgets.QLabel(self.page_1)
        self.lab_today_only_explain.setGeometry(QtCore.QRect(250, 355, 121, 21))
        self.lab_today_only_explain.setWordWrap(False)
        self.lab_today_only_explain.setObjectName("lab_today_only_explain")
        self.checkBox_todayonly = QtWidgets.QCheckBox(self.page_1)
        self.checkBox_todayonly.setGeometry(QtCore.QRect(230, 340, 120, 21))
        self.checkBox_todayonly.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_todayonly.setFont(font)
        self.checkBox_todayonly.setChecked(True)
        self.checkBox_todayonly.setTristate(False)
        self.checkBox_todayonly.setObjectName("checkBox_todayonly")
        self.frame = QtWidgets.QFrame(self.page_1)
        self.frame.setGeometry(QtCore.QRect(230, 150, 81, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 81, 115))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lab_cardtype = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_cardtype.sizePolicy().hasHeightForWidth())
        self.lab_cardtype.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_cardtype.setFont(font)
        self.lab_cardtype.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_cardtype.setObjectName("lab_cardtype")
        self.verticalLayout.addWidget(self.lab_cardtype)
        self.checkBox_card_new = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_card_new.setFont(font)
        self.checkBox_card_new.setAutoExclusive(True)
        self.checkBox_card_new.setObjectName("checkBox_card_new")
        self.verticalLayout.addWidget(self.checkBox_card_new)
        self.checkBox_card_learn = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_card_learn.setFont(font)
        self.checkBox_card_learn.setChecked(True)
        self.checkBox_card_learn.setAutoExclusive(True)
        self.checkBox_card_learn.setObjectName("checkBox_card_learn")
        self.verticalLayout.addWidget(self.checkBox_card_learn)
        self.checkBox_newANDreview = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_newANDreview.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_newANDreview.setFont(font)
        self.checkBox_newANDreview.setAutoExclusive(True)
        self.checkBox_newANDreview.setObjectName("checkBox_newANDreview")
        self.verticalLayout.addWidget(self.checkBox_newANDreview)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.checkBox_card_mature = QtWidgets.QCheckBox(self.page_1)
        self.checkBox_card_mature.setGeometry(QtCore.QRect(250, 260, 71, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_card_mature.setFont(font)
        self.checkBox_card_mature.setAutoExclusive(True)
        self.checkBox_card_mature.setObjectName("checkBox_card_mature")
        self.frame.raise_()
        self.tableWidget_users_connected.raise_()
        self.lab_users_connected.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.but_sendittt.raise_()
        self.checkBox_apply_resched.raise_()
        self.lab_batform_connected.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.progressBar_loading.raise_()
        self.checkBox_todayonly.raise_()
        self.checkBox_card_mature.raise_()
        self.lab_based_on_answers.raise_()
        self.lab_today_only_explain.raise_()
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.progressBar_waiting = QtWidgets.QProgressBar(self.page_2)
        self.progressBar_waiting.setGeometry(QtCore.QRect(50, 310, 291, 20))
        self.progressBar_waiting.setProperty("value", 1)
        self.progressBar_waiting.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_waiting.setTextVisible(False)
        self.progressBar_waiting.setInvertedAppearance(False)
        self.progressBar_waiting.setObjectName("progressBar_waiting")
        self.lab_plz_wait = QtWidgets.QLabel(self.page_2)
        self.lab_plz_wait.setGeometry(QtCore.QRect(40, 250, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lab_plz_wait.setFont(font)
        self.lab_plz_wait.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_plz_wait.setWordWrap(True)
        self.lab_plz_wait.setObjectName("lab_plz_wait")
        self.lab_real_winner = QtWidgets.QLabel(self.page_2)
        self.lab_real_winner.setGeometry(QtCore.QRect(50, 130, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.lab_real_winner.setFont(font)
        self.lab_real_winner.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_real_winner.setWordWrap(True)
        self.lab_real_winner.setObjectName("lab_real_winner")
        self.lab_real_winner_2 = QtWidgets.QLabel(self.page_2)
        self.lab_real_winner_2.setGeometry(QtCore.QRect(270, 180, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lab_real_winner_2.setFont(font)
        self.lab_real_winner_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_real_winner_2.setWordWrap(True)
        self.lab_real_winner_2.setObjectName("lab_real_winner_2")
        self.lab_real_winner_3 = QtWidgets.QLabel(self.page_2)
        self.lab_real_winner_3.setGeometry(QtCore.QRect(30, 20, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_real_winner_3.setFont(font)
        self.lab_real_winner_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_real_winner_3.setWordWrap(True)
        self.lab_real_winner_3.setObjectName("lab_real_winner_3")
        self.lab_real_winner_4 = QtWidgets.QLabel(self.page_2)
        self.lab_real_winner_4.setGeometry(QtCore.QRect(160, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lab_real_winner_4.setFont(font)
        self.lab_real_winner_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_real_winner_4.setWordWrap(True)
        self.lab_real_winner_4.setObjectName("lab_real_winner_4")
        self.lab_BA_logo = QtWidgets.QLabel(self.page_2)
        self.lab_BA_logo.setGeometry(QtCore.QRect(310, 30, 61, 61))
        self.lab_BA_logo.setText("")
        self.lab_BA_logo.setObjectName("lab_BA_logo")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.lab_bat_tit = QtWidgets.QLabel(self.page_3)
        self.lab_bat_tit.setGeometry(QtCore.QRect(40, 40, 331, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lab_bat_tit.setFont(font)
        self.lab_bat_tit.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_bat_tit.setObjectName("lab_bat_tit")
        self.progressBar_p1 = QtWidgets.QProgressBar(self.page_3)
        self.progressBar_p1.setGeometry(QtCore.QRect(20, 140, 371, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_p1.sizePolicy().hasHeightForWidth())
        self.progressBar_p1.setSizePolicy(sizePolicy)
        self.progressBar_p1.setMinimumSize(QtCore.QSize(250, 50))
        self.progressBar_p1.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_p1.setFont(font)
        self.progressBar_p1.setProperty("value", 24)
        self.progressBar_p1.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_p1.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_p1.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_p1.setObjectName("progressBar_p1")
        self.progressBar_p2 = QtWidgets.QProgressBar(self.page_3)
        self.progressBar_p2.setGeometry(QtCore.QRect(20, 270, 371, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_p2.sizePolicy().hasHeightForWidth())
        self.progressBar_p2.setSizePolicy(sizePolicy)
        self.progressBar_p2.setMinimumSize(QtCore.QSize(250, 50))
        self.progressBar_p2.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.progressBar_p2.setFont(font)
        self.progressBar_p2.setProperty("value", 24)
        self.progressBar_p2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_p2.setObjectName("progressBar_p2")
        self.stackedWidget.addWidget(self.page_3)
        BatMainWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(BatMainWin)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BatMainWin)

    def retranslateUi(self, BatMainWin):
        _translate = QtCore.QCoreApplication.translate
        BatMainWin.setWindowTitle(_translate("BatMainWin", "Battle Anki"))
        self.tableWidget_users_connected.setSortingEnabled(True)
        self.lab_users_connected.setText(_translate("BatMainWin", "Select your options, click a name, then sendittt"))
        self.lab_numcards.setText(_translate("BatMainWin", "Cards:"))
        self.lab_max_cards.setText(_translate("BatMainWin", "Max 500 cards"))
        self.but_sendittt.setText(_translate("BatMainWin", "Send ittt"))
        self.checkBox_apply_resched.setText(_translate("BatMainWin", "Apply rescheduling?"))
        self.lab_batform_connected.setText(_translate("BatMainWin", "Welcome to Battle Anki!"))
        self.checkBox_match_q.setText(_translate("BatMainWin", "Matched Deck?"))
        self.lab_matched_desc.setText(_translate("BatMainWin", "Identical cards for both players"))
        self.progressBar_loading.setFormat(_translate("BatMainWin", "Loading... %p%"))
        self.lab_based_on_answers.setText(_translate("BatMainWin", "if left unchecked, these cards won\'t count"))
        self.lab_today_only_explain.setText(_translate("BatMainWin", "cards due today only"))
        self.checkBox_todayonly.setText(_translate("BatMainWin", "Bailey Mode"))
        self.lab_cardtype.setText(_translate("BatMainWin", "Card Type"))
        self.checkBox_card_new.setText(_translate("BatMainWin", "New"))
        self.checkBox_card_learn.setText(_translate("BatMainWin", "Review"))
        self.checkBox_newANDreview.setText(_translate("BatMainWin", "Both"))
        self.checkBox_card_mature.setText(_translate("BatMainWin", "Mature"))
        self.progressBar_waiting.setFormat(_translate("BatMainWin", "%p%"))
        self.lab_plz_wait.setText(_translate("BatMainWin", "Get ready...\n"
"if they accept, the game will start!"))
        self.lab_real_winner.setText(_translate("BatMainWin", "\"The real winner is the one\n"
"          who learns the most...\""))
        self.lab_real_winner_2.setText(_translate("BatMainWin", "- CIMED Student"))
        self.lab_real_winner_3.setText(_translate("BatMainWin", "\"Battle Anki makes normal Anki\n"
" more enjoyable and engaging\""))
        self.lab_real_winner_4.setText(_translate("BatMainWin", "- CIMED Student"))
        self.lab_bat_tit.setText(_translate("BatMainWin", "The Anki Battle is on!!!"))
